fname = input("Whats your First name")
lname = input("Whats your Last name")
age = input("How old are you")
WTV = input("What do you like to do")
print(fname +" "+ lname +" "+ "is " + age +" "+ "years old" + " and likes to" +" "+ WTV)
